from typing import Any

from repetition_analyzer.parse import Entry

def find_exact_duplicates(entries: list[Entry]) -> list[dict[str, Any]]: ...
def find_near_duplicates(entries: list[Entry], threshold: float) -> list[dict[str, Any]]: ...
def extract_ngrams(entries: list[Entry], min_n: int, max_n: int, min_count: int) -> list[dict[str, Any]]: ...
def find_all_sequences(entries: list[Entry], min_len: int, max_len: int, min_occurrences: int, similarity_threshold: float) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]: ...
