from typing import Any

def normalize(text: str) -> str: ...
def find_near_duplicates(entries: list[tuple[int, str, str]], threshold: float) -> list[dict[str, Any]]: ...
def extract_ngrams(entries: list[tuple[int, str, str]], min_n: int, max_n: int, min_count: int) -> list[dict[str, Any]]: ...
def find_repeated_sequences(entries: list[tuple[int, str, str]], min_len: int, max_len: int, min_occurrences: int) -> list[dict[str, Any]]: ...
def find_near_duplicate_sequences(entries: list[tuple[int, str, str]], min_len: int, max_len: int, threshold: float, min_occurrences: int, exact_sequences: list[dict[str, Any]]) -> list[dict[str, Any]]: ...
